config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  use_doorkeeper_openid_connect

  devise_for :users, path: 'identity', sign_out_via: %i[get post delete], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/passthru/last', to: 'passthru#last', as: :back_to_etm

  namespace :identity do
    get '/', to: redirect('/identity/profile')
    get 'profile', to: 'settings#index', as: :profile

    get 'change_name', to: 'settings#edit_name', as: :edit_name
    post 'change_name', to: 'settings#update_name'

    get 'change_email', to: 'settings#edit_email', as: :edit_email
    post 'change_email', to: 'settings#update_email'

    get 'change_password', to: 'settings#edit_password', as: :edit_password
    post 'change_password', to: 'settings#update_password'

    post 'change_scenario_privacy', to: 'settings#update_scenario_privacy'

    get 'subscription/:audience', to: 'newsletter#edit', as: :edit_subscription
    patch 'subscription/:audience', to: 'newsletter#update', as: :update_subscription

    resources :tokens, only: [:index, :new, :create, :destroy], as: :tokens
    resources :access_tokens, only: [:create], as: :access_tokens
    resources :authorized_applications, only: [:index], as: :authorized_applications
  end

  devise_scope :user do
    get 'identity/delete_account', to: 'users/registrations#confirm_destroy', as: :delete_account
  end

  root :to => "saved_scenarios#index"

  resources :saved_scenarios do
    resource :feature, only: %i[show create update destroy], controller: 'featured_scenarios' do
      get :confirm_destroy
    end

    collection do
      get :list
      post :list
      post :index
    end

    member do
      put :publish
      put :unpublish
      put :discard
      put :undiscard
      get :confirm_destroy
    end

    resources :users, controller: 'saved_scenario_users' do
      member do
        get :confirm_destroy
      end
    end

    get '/history' => 'saved_scenario_history#index'
    put '/history/:scenario_id' => 'saved_scenario_history#update',  as: :update_history
    put '/history/:scenario_id/restore' => 'saved_scenario_history#restore',  as: :restore_history
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: %i[index show create update destroy]
      resources :saved_scenarios, only: %i[index show create update destroy] do
        resources :users, only: %i[index create], controller: 'saved_scenario_users' do
          collection do
            put :update
            delete :destroy
          end
        end
      end
      resources :featured_scenarios, only: %i[index show] do
        collection { get :scenarios }
      end
      resources :versions, only: [:index]
    end
  end

  resources :collections, only: %i[index show new edit destroy update] do
    collection do
      get :list
      post :list
      get :new_transition
      post :create_transition
      post :create_collection, as: :create
      post :index
    end

    member do
      put :discard
      put :undiscard
      get :confirm_destroy
    end
  end

  resources :discarded do
    collection do
      get :index
      post :index
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/org')
    get 'org',              to: 'users#org'
    get 'user/:user_id',         to: 'users#edit',    as: :edit_user
    put 'user/:user_id',         to: 'users#update',  as: :update_user
    put 'user/:user_id/confirm', to: 'users#confirm', as: :confirm_user

    get 'applications', to: 'staff_applications#index'
    put 'applications', to: 'staff_applications#update'

    resources :users, only: [:index] do
      collection do
        get :list
        post :list
        post :index
      end
    end

    resources :featured_scenario_users

    resources :saved_scenarios, only: [:index] do
      collection do
        get :list
        post :list
        post :index
        post :batch_dump
      end
    end

    resources :collections, only: [:index] do
      collection do
        post :list
        get :list
        post :index
      end
    end
  end

  get :contact, to: 'static_pages#contact'
  post :send_message, to: 'static_pages#send_message'
  get :privacy, to: 'static_pages#privacy'
  get :terms,   to: 'static_pages#terms'
  get :collaborate,   to: 'static_pages#collaborate'
  # get :root,    to: 'static_pages#empty'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/collections_controller.rb
module Admin
  class CollectionsController < ApplicationController
    include AdminController
    include Pagy::Method
    include Filterable

    def index
      # Include Pagy to paginate @collections or any other resource
      @pagy_collections, @collections = pagy(
        Collection.kept.order(created_at: :desc)
      )

      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    # Renders a partial of collections based on turbo search and filters
    #
    # GET admin/collections/list
    def list
      filtered = filter!(Collection)

      @pagy_collections, @collections =  pagy(filtered.kept)

      respond_to do |format|
        format.html { render(
          partial: "collections",
          locals: { collections: @collections, pagy_collections: @pagy_collections }
        ) }
        format.turbo_stream { render(:index) }
      end
    end
  end
end

app/controllers/api/v1/collections_controller.rb
module Api
  module V1
    class CollectionsController < BaseController            
      wrap_parameters false

      check_authorization

      load_and_authorize_resource(class: Collection, only: %i[index show destroy update])

      before_action only: %i[create] do
        # Only check that the user can create, don't load resource as association is not yet made.
        authorize!(:create, Collection)
      end

      # GET /api/v1/collections
      def index
        collections = current_user.collections.kept.order(created_at: :desc)

        render json: {
          collections: collections.as_json
        }, status: :ok
      end

      # GET /api/v1/collections/:id
      def show
        render json: @collection.as_json, status: :ok
      end

      # POST /api/v1/collections
      def create
        Api::CreateCollection.new.call(
          user: current_user,
          params: collection_params.to_h.symbolize_keys
        ).either(
          ->(collection)   { render json: collection, status: :created },
          ->(errors) { render json: errors, status: :unprocessable_entity }
        )
      end

      # PUT /api/v1/collection/:id
      def update
        Api::UpdateCollection.new.call(
          collection: @collection,
          params: collection_params.to_h.symbolize_keys
        ).either(
          ->(collection)   { render json: collection, status: :ok },
          ->(errors) { render json: errors, status: :unprocessable_entity }
        )
      end

      # DELETE /api/v1/collections/:id
      def destroy
        if @collection.destroy
          head :no_content
        else
          render json: { errors: @collection.errors.full_messages }, status: :unprocessable_entity
        end
      end

      private

      def collection_params
        # Support both flat and nested collection params (Make sure there is no automatic wrapping)
        coll_params = params[:collection].present? ? params.require(:collection) : params
        coll_params.permit(:title, :area_code, :end_year, :version, :interpolation, :discarded, saved_scenario_ids: [], scenario_ids: [])
      end
    end
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  include Pagy::Method
  include Filterable

  load_resource only: %i[discard undiscard new_transition create_transition confirm_destroy]
  load_and_authorize_resource only: %i[show new edit destroy update]

  before_action :require_user, only: %i[index create_collection new_transition create_transition]
  before_action :ensure_valid_config
  before_action :welcome_back

  before_action only: %i[discard undiscard confirm_destroy] do
    authorize!(:destroy, @collection)
  end

  # GET /collections or /collections.json
  def index
    @pagy_collections, @collections = pagy(user_collections)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # Renders a partial of collections based on turbo search and filters
  #
  # GET /collections/list
  def list
    filtered = filter!(Collection).kept.where(user: current_user)

    @pagy_collections, @collections = pagy(filtered)

    respond_to do |format|
      format.html { render(
        partial: "collections",
        locals: { collections: @collections, pagy_collections: @pagy_collections }
      ) }
      format.turbo_stream { render(:index) }
    end
  end

  # Create a new collection of saved scenarios
  #
  # GET /collections/new
  def new
    @collection = current_user.collections.build(interpolation: false)
    @scenarios = current_user.saved_scenarios.available.order(updated_at: :desc)
    @versions = @scenarios.map(&:version).uniq

    respond_to do |format|
      format.html { render layout: "application" }
    end
  end

  # GET /collections/1/edit
  def edit
    @scenarios = current_user.saved_scenarios
      .available
      .where(version: @collection.version)
      .order(updated_at: :desc)
  end

  def update
    respond_to do |format|
      if @collection.update(update_collection_params)
        format.html { redirect_to @collection, notice: t("collections.succesful_update") }
        format.json { render json: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @collection.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # Create a new collection from an interpolation of a saved scenario
  #
  # GET /collections/new_transition
  def new_transition
    @saved_scenarios = elegible_scenarios
    @collection = new_transition_collection
  end

  def show
    @editable = @collection.user == current_user
    respond_to do |format|
      format.html { render layout: "application" }
    end
  end

  # Creates a new Collection record based on the scenario specified in the
  # params. This is the interpolation route
  #
  # Redirects to the external MYC app when successful.
  #
  # POST /collections/create_transition
  def create_transition
    saved_scenario = current_user.saved_scenarios.find(create_transition_params[:saved_scenario_ids])

    result = CreateInterpolatedCollection.call(
      engine_client(saved_scenario.version),
      saved_scenario,
      current_user
    )

    if result.successful?
      redirect_to collection_path(result.value)
    else
      flash[:alert] = result.errors.join(", ")
      @collection = new_transition_collection
      @saved_scenarios = elegible_scenarios

      render :new_transition, status: :unprocessable_entity
    end
  end

  def create_collection
    collection = current_user.collections.build(
      title: collection_title,
      version: create_collection_params[:version],
      interpolation: false
    )

    create_collection_params[:saved_scenario_ids].uniq.reject(&:empty?).each.with_index(1) do |saved_scenario_id, saved_scenario_order|
      collection.collection_saved_scenarios.build(saved_scenario_id:, saved_scenario_order:)
    end

    if collection.valid?
      collection.save
      redirect_to collection_path(collection)
    else
      flash[:alert] = t("collections.failure")
      redirect_to collections_path
    end
  end

  def confirm_destroy
    render :confirm_destroy, layout: "application"
  end

  # Removes a Collection record.
  #
  # DELETE /collections/:id
  def destroy
    DeleteCollection.call(
      engine_client(@collection.version),
      @collection
    )

    redirect_to collections_path
  end

  # Soft-deletes the myc so that it no longer appears in listings.
  #
  # PUT /collections/:id/discard
  def discard
    unless @collection.discarded?
      @collection.discarded_at = Time.zone.now
      @collection.save(touch: false)

      flash.notice = t("trash.discarded_flash")
      flash[:undo_params] = [ undiscard_collection_path(@collection), { method: :put } ]
    end

    redirect_to(collection_path(@collection))
  end

  # Removes the soft-deletes of the scenario.
  #
  # PUT /collections/:id/undiscard
  def undiscard
    unless @collection.kept?
      @collection.discarded_at = nil
      @collection.save(touch: false)

      flash.notice = t("trash.undiscarded_flash")
      flash[:undo_params] = [ discard_collection_path(@collection), { method: :put } ]
    end

    redirect_back(fallback_location: discarded_path)
  end

  private

  def user_collections
    current_user
      .collections
      .kept
      .order(created_at: :desc)
  end

  def ensure_valid_config
    return if Settings.collections.uri

    redirect_to root_path,
      notice: "Missing collections.uri setting in config.yml"
  end

  def update_collection_params
    params.require(:collection).permit(:title, saved_scenario_ids: [])
  end

  def create_collection_params
    params.require(:collection).permit(:title, :version, saved_scenario_ids: [])
  end

  def create_transition_params
    params.require(:collection).permit(:version, :saved_scenario_ids)
  end

  def filter_params
    params.permit(:title)
  end

  def new_transition_collection
    current_user.collections.build(interpolation: true)
  end

  def elegible_scenarios
    current_user.saved_scenarios.available.where(end_year: 2050).order(updated_at: :desc)
  end

  def collection_title
    title = create_collection_params[:title]
    title.empty? ? t("collections.no_title") : title
  end
end

app/helpers/collections_helper.rb
# frozen_string_literal: true

module CollectionsHelper
  # Public: The full URL to the Collections application for an instance of
  # Collections.
  #
  # Returns a string.
  def collection_url(collection)
    CollectionUrlBuilder.collections_app_url(collection)
  end

  def can_use_as_myc_scenario?(saved_scenario)
    saved_scenario.end_year == 2050
  end
end

app/views/collections/_block_right_menu.html.erb
<% content_for :block_right do %>
  <div class="flex flex-col">
  <% if %w[index list].include?(action_name) %>
    <% if has_collections %>
      <%= form_with url: list_collections_path,
        method: :get,
        data: { controller: "search-form", search_form_target: "form", turbo_frame: "collections", 'turbo-method': "get" } do |form|
        %>
        <div class="flex flex-col pl-5">
          <div class="mb-5 flex text-midnight-800">
            <%= form.text_field :title,
              placeholder: t('collections.search_by_title'),
              class: "p-2 text-sm",
              autocomplete: "off",
              data: { action: "input->search-form#search" }
            %>
            <%= heroicon 'magnifying-glass', options: {class: 'w-5 h-5 ml-2 my-auto'} %>
          </div>
          <div>
            <%= form.check_box :interpolated,
              class: "rounded-md mr-5 border-midnight-400 !checked:bg-midnight-920 text-midnight-920",
              data: { action: "input->search-form#search" }
            %>
            <%= form.label :interpolated, t('collections.filter.transition') ,
              class: "text-sm text-midnight-450"
            %>
          </div>
          <div class="mt-2">
            <%= form.check_box :plain,
              class: "rounded-md mr-5 border-midnight-400 !checked:bg-midnight-920 text-midnight-920",
              data: { action: "input->search-form#search" }
            %>
            <%= form.label :plain, t('collections.filter.plain'),
              class: "text-sm text-midnight-450"
            %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: collections_path,
      title: t('collections.all'),
      icon: 'arrow-left',
      active: controller_name == 'collections' && action_name == 'index')
    )%>
  <% end %>
  </div>

  <div class="border-l lg:border-l-0 lg:border-t flex flex-col border-solid border-gray-200 pr-5 lg:pr-0 lg:mt-10 lg:pt-10">

    <%= render(partial: "block_right_sub_options") %>

  </div>
<% end %>

app/views/collections/_block_right_sub_options.html.erb
<%= render(Hovercard::Component.new(
    path: '',
    text: t("collections.block_right.compose_collection.description")
  )) do %>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: new_collection_path,
      title: t("collections.block_right.compose_collection.title"),
      icon: 'plus',
      active: controller_name == 'collections' && action_name == 'new',
      static: true)
    )%>
<% end %>
<%= render(Hovercard::Component.new(
    path: '',
    text: t("collections.block_right.create_transition.description")
  )) do %>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: new_transition_collections_path,
      title: t("collections.block_right.create_transition.title"),
      icon: 'plus',
      active: controller_name == 'collections' && action_name == 'new_transition',
      static: true)
    )%>
<% end %>

app/views/collections/_collections.html.erb
<%= turbo_frame_tag "collections" do %>
  <%= render(PagyComponent.new(pagy_objects: pagy_collections)) do %>
    <div id="collections_list">
      <% collections.each do |collection| %>
        <%= render(Collections::Row::Component.new(path: collection_path(collection), collection: collection)) %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/collections/confirm_destroy.html.erb
<%= render(ModalComponent.new(title: t('.title'))) do |modal| %>
  <%= turbo_frame_tag :modal do %>
    <%= form_for(@collection, url: collection_path(@collection), html: { method: :delete, data: { turbo: false } }) do |f| %>
      <div class="flex-col mb-10">
        <div class="flex text-red-600 mb-5">
          <span class="mr-5"><%= heroicon 'exclamation-triangle', options: { class: 'w-6 h-6' } %></span>
          <span class="text-base">
            <%= t('.warning_header') %>
          </span>
        </div>
        <p class="mb-2">
          <%= t('.warning') %>
        </p>
        <p class="text-sm text-midnight-450">
          <%= t('.irreversible') %>
        </p>
      </div>
      <div class="mt-6 pb-2 flex items-center gap-2">
        <%= button_tag t('.submit'), class: button_classes("text-base", size: :lg, color: :warning) %>
        <%= modal.close_link(t('identity.cancel'), collection_path(@collection), class: button_classes("text-base", size: :lg)) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/collections/edit.html.haml
- content_for :title, "Editing #{@collection.title} - #{t('collections.title')} - #{t('meta.title')}"
- content_for :menu_title, "Editing #{@collection.title}"
= render(partial: 'collections/edit/block_right_menu', locals: { collection: @collection })

= form_for(@collection, url: collection_path(@collection), html: { data: { controller: 'collections' }, method: :put, class: 'flex flex-col h-full' }) do |f|
  = f.label :title, t('scenario.title'), class: 'text-sm text-gray-400 mb-2'
  = f.text_field :title, class: 'appearance-none w-1/2 rounded-md border-gray-200 mb-5'

  .mt-5
    .text-sm.text-gray-400{ data: { collections_target: 'sortableListLabel' } }= t('collections.edit.instructions')
    .mt-5{ data: { collections_target: 'sortableList' } }
      - @collection.saved_scenarios.each do |scenario|
        = render(Collections::SortableSavedScenario::Component.new(         |
          form: f,                                                          |
          path: saved_scenario_path(scenario),                              |
          saved_scenario: scenario,                                         |
          access: !scenario.private? || scenario.viewer?(current_user)))    |
      - @scenarios.each do |scenario|
        - if (!@collection.saved_scenarios.include?(scenario))
          = render(Collections::SortableSavedScenario::Component.new(       |
            hidden: true,                                                   |
            form: f,                                                        |
            path: saved_scenario_path(scenario),                            |
            saved_scenario: scenario,                                       |
            access: !scenario.private? || scenario.viewer?(current_user)))  |

  .mt-5.text-sm.text-gray-400.mb-2{ data: { collections_target: 'listPickerLabel' }}= t('collections.edit.picker')
  .mt-5.flex.flex-wrap{ data: { collections_target: 'listPicker' } }
    - if @scenarios.present?
      - @scenarios.each do |scenario|
        = render(Collections::ScenarioPicker::Component.new(                |
          scenario: scenario,                                               |
          hidden: @collection.saved_scenarios.include?(scenario)))          |
    - else
      = t('collections.new.no_scenarios')

  .flex.mt-10
    = submit_tag t('scenario.save'), class: 'button button-primary mr-5', data: { collections_target: 'saveButton' }
    = link_to t('collections.new.form.cancel'), collection_path(@collection), class: 'button'

app/views/collections/index.html.haml
- content_for :title, t('collections.title')
- content_for :menu_title, t('collections.title')
= render(partial: "block_right_menu", locals: { has_collections: @collections.present? })

- if @collections.present?
  = render(partial: "collections", locals: {pagy_collections: @pagy_collections, collections: @collections})
- else
  .text-sm.text-midnight-400.mb-2=t('collections.try_now')
  .text-readable-width.get-started= t('collections.get_started')

app/views/collections/index.turbo_stream.erb
<%= turbo_stream.append "collections_list" do %>
  <% @collections.each do |collection| %>
    <%= render(Collections::Row::Component.new(path: collection_path(collection), collection: collection)) %>
  <% end %>
<% end %>
<%= turbo_stream.update "next_url" do %>
  <%= render(MorePagy::Component.new(pagy:@pagy_collections)) %>
<% end %>

app/views/collections/new.html.haml
- content_for :title, t('collections.new.title')
- content_for :menu_title, t('collections.new.title')
= render(partial: 'block_right_menu')

.text-readable-width.text-midnight-400.mb-10
  = t('collections.new_collection.description')

= form_for(@collection, url: create_collections_path, html: { method: :post, class: 'flex flex-col h-full', data: { controller: 'collections' } }) do |f|
  = f.label :title, t('scenario.title'), class: 'text-sm text-gray-400 mb-2'
  = f.text_field :title, class: 'appearance-none w-1/2 rounded-md border-gray-200 mb-5', placeholder: t('collections.new.form.default_title')

  = f.hidden_field :version, value: @versions.first.tag, data: { collections_target: 'hiddenVersion' }
  - if @versions.count > 1
    = f.label :version, t('collections.new.form.version'), class: 'text-sm text-gray-400 mb-2'
    = select_tag nil,                                                                             |
      options_for_select(@versions.map { |v| [v.titleize, v.tag] }, @versions.first.tag),         |
      data: { action: 'collections#changeVersion', collections_target: 'versionSelect' },         |
      class: 'appearance-none w-1/2 rounded-md border-gray-200 mb-5'                              | 

  .mt-5
    .text-sm.text-gray-400{ data: { collections_target: 'sortableListLabel' } }= t('collections.edit.instructions')
    .mt-5{ data: { collections_target: 'sortableList' } }
      - @scenarios.each do |scenario|
        = render(Collections::SortableSavedScenario::Component.new(       |
          hidden: true,                                                   |
          form: f,                                                        |
          path: saved_scenario_path(scenario),                            |
          saved_scenario: scenario,                                       |
          access: !scenario.private? || scenario.viewer?(current_user)))  |

  .mt-5.text-sm.text-gray-400.mb-2{ data: { collections_target: 'listPickerLabel' }}= t('collections.edit.picker')
  .mt-5.flex.flex-wrap{ data: { collections_target: 'listPicker' } }
    - if @scenarios.present?
      - @scenarios.each do |scenario|
        = render(Collections::ScenarioPicker::Component.new(              |
          scenario: scenario))                                            |
    - else
      = t('collections.new.no_scenarios')

  .flex.mt-10
    = submit_tag t('scenario.save'), class: 'button button-primary mr-5', data: { collections_target: 'saveButton' }
    = link_to t('collections.new.form.cancel'), collections_path, class: 'button'

app/views/collections/new_transition.html.erb
<% content_for :title, t('collections.new_transition.title') %>
<% content_for :menu_title, t('collections.new_transition.title') %>
<%= render(partial: "block_right_menu") %>

<div class="text-readable-width text-midnight-400 mb-10">
  <%= t('collections.new_transition.description') %>
</div>

<%= form_for(
  @collection,
  url: create_transition_collections_path,
  html: { method: :post, class: 'flex flex-col h-full',
  data: {controller: 'collections'} }) do |f| %>

  <% if @saved_scenarios.present? %>
    <div class="flex flex-wrap">
      <% @saved_scenarios.each do |scenario| %>
        <%= render(Collections::InterpolationSavedScenario::Component.new(
            form: f,
            id: scenario.id,
            title: scenario.title,
            end_year: scenario.end_year,
            area: t("areas.#{scenario.area_code}")
          ))%>
      <% end %>
    </div>
  <% else %>
    <%= t('collections.new_transition.no_scenarios') %>
  <% end %>

  <div class="flex mt-10">
    <% if @saved_scenarios.present? %>
      <%= submit_tag t('collections.new_transition.start'), class: 'button button-primary mr-5' %>
    <% end %>
    <%= link_to t('collections.new.form.cancel'), collections_path, class: 'button' %>
  </div>
<% end %>

app/views/collections/show.html.erb
<%- content_for :menu_title do %>
  <%= @collection.title %>
<% end %>
<%- content_for :title, "#{@collection.title} - #{t('collections.title')} - #{t('meta.title')}" %>
<%= render(partial: "collections/show/block_right_menu", locals: { collection: @collection })%>

<%= render(Collections::Info::Component.new(
    path: collection_url(@collection),
    button_title: t('collections.open'),
    collection: @collection,
    time: time_ago_in_words(@collection.updated_at))
)%>

<% if @collection.discarded?%>
  <%= render(NoticeBanner::TrashComponent.new(text: t('trash.notice.collections', deleted_after: Collection::AUTO_DELETES_AFTER.in_days.to_i)))%>
<% end %>

<div class="w-min mb-5">
  <%= render(HovercardWithVersion::Component.new(version: @collection.version.tag))%>
</div>

<div class="pt-5 border-t border-solid border-gray-200">
  <% if @collection.interpolated? %>
    <%= t('collections.interpolated.long_description') %>

    <% if @collection.saved_scenarios.present? %>
      <div class="mt-5 text-midnight-400 text-sm">
        <%= t('collections.interpolated.based_on') %>
      </div>
      <div class="w-fit">
        <%= render(Collections::SavedScenario::Component.new(
          path: saved_scenario_path(@collection.saved_scenarios.first),
          saved_scenario: @collection.saved_scenarios.first,
          access: !@collection.saved_scenarios.first.private? || @collection.saved_scenarios.first.viewer?(current_user)
        ))%>
      </div>
    <% end %>
  <% elsif @collection.saved_scenarios.present? %>
    <%= t('collections.contains') %>
    <div class="mt-5">
      <% @collection.saved_scenarios.each do |saved_scenario| %>
        <%= render(Collections::SavedScenario::Component.new(
          path: saved_scenario_path(saved_scenario),
          saved_scenario: saved_scenario,
          access: !saved_scenario.private? || saved_scenario.viewer?(current_user)
        ))%>
      <% end %>
    </div>
  <% end %>
</div>