config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  use_doorkeeper_openid_connect

  devise_for :users, path: 'identity', sign_out_via: %i[get post delete], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/passthru/last', to: 'passthru#last', as: :back_to_etm

  namespace :identity do
    get '/', to: redirect('/identity/profile')
    get 'profile', to: 'settings#index', as: :profile

    get 'change_name', to: 'settings#edit_name', as: :edit_name
    post 'change_name', to: 'settings#update_name'

    get 'change_email', to: 'settings#edit_email', as: :edit_email
    post 'change_email', to: 'settings#update_email'

    get 'change_password', to: 'settings#edit_password', as: :edit_password
    post 'change_password', to: 'settings#update_password'

    post 'change_scenario_privacy', to: 'settings#update_scenario_privacy'

    get 'subscription/:audience', to: 'newsletter#edit', as: :edit_subscription
    patch 'subscription/:audience', to: 'newsletter#update', as: :update_subscription

    resources :tokens, only: [:index, :new, :create, :destroy], as: :tokens
    resources :access_tokens, only: [:create], as: :access_tokens
    resources :authorized_applications, only: [:index], as: :authorized_applications
  end

  devise_scope :user do
    get 'identity/delete_account', to: 'users/registrations#confirm_destroy', as: :delete_account
  end

  root :to => "saved_scenarios#index"

  resources :saved_scenarios do
    resource :feature, only: %i[show create update destroy], controller: 'featured_scenarios' do
      get :confirm_destroy
    end

    collection do
      get :list
      post :list
      post :index
    end

    member do
      put :publish
      put :unpublish
      put :discard
      put :undiscard
      get :confirm_destroy
    end

    resources :users, controller: 'saved_scenario_users' do
      member do
        get :confirm_destroy
      end
    end

    get '/history' => 'saved_scenario_history#index'
    put '/history/:scenario_id' => 'saved_scenario_history#update',  as: :update_history
    put '/history/:scenario_id/restore' => 'saved_scenario_history#restore',  as: :restore_history
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: %i[index show create update destroy]
      resources :saved_scenarios, only: %i[index show create update destroy] do
        resources :users, only: %i[index create], controller: 'saved_scenario_users' do
          collection do
            put :update
            delete :destroy
          end
        end
      end
      resources :featured_scenarios, only: %i[index show] do
        collection { get :scenarios }
      end
      resources :versions, only: [:index]
    end
  end

  resources :collections, only: %i[index show new edit destroy update] do
    collection do
      get :list
      post :list
      get :new_transition
      post :create_transition
      post :create_collection, as: :create
      post :index
    end

    member do
      put :discard
      put :undiscard
      get :confirm_destroy
    end
  end

  resources :discarded do
    collection do
      get :index
      post :index
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/org')
    get 'org',              to: 'users#org'
    get 'user/:user_id',         to: 'users#edit',    as: :edit_user
    put 'user/:user_id',         to: 'users#update',  as: :update_user
    put 'user/:user_id/confirm', to: 'users#confirm', as: :confirm_user

    get 'applications', to: 'staff_applications#index'
    put 'applications', to: 'staff_applications#update'

    resources :users, only: [:index] do
      collection do
        get :list
        post :list
        post :index
      end
    end

    resources :featured_scenario_users

    resources :saved_scenarios, only: [:index] do
      collection do
        get :list
        post :list
        post :index
        post :batch_dump
      end
    end

    resources :collections, only: [:index] do
      collection do
        post :list
        get :list
        post :index
      end
    end
  end

  get :contact, to: 'static_pages#contact'
  post :send_message, to: 'static_pages#send_message'
  get :privacy, to: 'static_pages#privacy'
  get :terms,   to: 'static_pages#terms'
  get :collaborate,   to: 'static_pages#collaborate'
  # get :root,    to: 'static_pages#empty'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/saved_scenario/featured.rb
# frozen_string_literal: true

# Contains methods concerning featured scenarios
module SavedScenario::Featured
  def featured?
    featured_scenario.present?
  end

  def featured_owner_name
    featured? && featured_scenario.owner.present? ? featured_scenario.owner.name : owners.first.name
  end

  def localized_title(locale)
    featured? ? featured_scenario.localized_title(locale) : title
  end

  def localized_description(locale)
    featured? ? featured_scenario.localized_description(locale) : description
  end
end

app/controllers/admin/saved_scenarios_controller.rb
module Admin
  class SavedScenariosController < ApplicationController
    include AdminController
    include Pagy::Method
    include Filterable

    # GET /admin/saved_scenarios
    def index
      @pagy_admin_saved_scenarios, @saved_scenarios = pagy(admin_saved_scenarios)
      @filtered_ids = admin_saved_scenarios.pluck(:id)
      @filters = {
        featured: true,
        area_codes: area_codes_for_filter,
        end_years: admin_saved_scenarios.pluck(:end_year).tally,
        versions: admin_saved_scenarios.joins(:version).pluck("version.tag", "version.id").uniq
      }

      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    # Renders a partial of saved_scenarios based on turbo search and filters
    #
    # GET admin/saved_scenarios/list
    def list
      filtered = filter!(SavedScenario)
        .available
        .includes(:featured_scenario, :users)

      @pagy_admin_saved_scenarios, @saved_scenarios = pagy(filtered)
      @filtered_ids = filtered.pluck(:id)

      respond_to do |format|
        format.html { render(
          partial: "saved_scenarios",
          locals: {
            saved_scenarios: @saved_scenarios,
            pagy_admin_saved_scenarios: @pagy_admin_saved_scenarios,
            filtered_ids: @filtered_ids
          }
        ) }
        format.turbo_stream { render(:index) }
      end
    end

    # POST admin/saved_scenarios/batch_dump
    #
    # Creates a dump of multiple saved scenarios as an ETM file (Zstandard-compressed JSON)
    def batch_dump
      result = SavedScenarioPacker::Dump.new(
        saved_scenario_ids,
        streaming_engine_client(Version.default),
        current_user
      ).call

      if result.success?
        dump = result.value!
        send_file(
          dump.file_path,
          filename: File.basename(dump.file_path),
          type: "application/x-etm",
          disposition: "attachment"
        )
      else
        flash[:alert] = result.failure
        redirect_to admin_saved_scenarios_path
      end
    end

    private

    def admin_saved_scenarios
      @admin_saved_scenarios ||= SavedScenario
        .available
        .includes(:featured_scenario, :users)
        .order(created_at: :desc)
    end

    # Make sure to group all dup area_codes for nl together
    def area_codes_for_filter
      area_codes = admin_saved_scenarios.pluck(:area_code).tally

      dups = area_codes.select { |k, _v| SavedScenario::AREA_DUPS.include?(k) }

      if dups.size > 1
        area_codes = area_codes.except(*dups.keys)
        area_codes[dups.keys.first] = dups.sum { |_k, v| v }
      end

      area_codes.sort_by { |_k, v| v }.reverse
    end

    def saved_scenario_ids
      params.require(:saved_scenario_ids)
    end
  end
end

app/controllers/api/v1/saved_scenarios_controller.rb
module Api
  module V1
    class SavedScenariosController < BaseController
      check_authorization

      load_and_authorize_resource(class: SavedScenario, only: %i[index create show update destroy])

      # GET /saved_scenarios or /saved_scenarios.json
      def index
        base =
          if params[:scope] == "all"
            SavedScenario.accessible_by(current_ability)
          elsif current_user
            current_user
              .saved_scenarios
              .accessible_by(current_ability)
          else
            SavedScenario.none
          end

        @saved_scenarios = base
          .available
          .includes(:featured_scenario, :users)
          .order(updated_at: :desc)

        render json: @saved_scenarios
      end

      # GET /saved_scenarios/:id
      def show
        render json: @saved_scenario
      end

      # POST api/v1/saved_scenarios
      def create
        result = SavedScenario::Create.call(
          engine_client,
          saved_scenario_params,
          current_user
        )

        if result.successful?
          render json: result.value, status: :created
        else
          render json: { errors: result.errors }, status: :unprocessable_entity
        end
      end

      # PATCH/PUT api/v1/saved_scenarios/1
      def update
        result = SavedScenario::Update.call(
          engine_client,
          @saved_scenario,
          saved_scenario_params.except(:version)
        )

        if result.successful?
          render json: result.value, status: :ok
        else
          render json: { errors: result.errors }, status: :unprocessable_entity
        end
      end

      # DELETE /saved_scenarios/1 or /saved_scenarios/1.json
      def destroy
        if @saved_scenario.destroy
          render json: { message: "Scenario deleted successfully" }, status: :ok
        else
          render json: { error: "Failed to delete scenario" }, status: :unprocessable_entity
        end
      end

      private

      # Only allow a list of trusted parameters through.
      def saved_scenario_params
        params.require(:saved_scenario).permit(
          :scenario_id, :title, :version,
          :description, :area_code, :end_year, :private, :discarded
        )
      end

      def engine_client
        MyEtm::Auth.engine_client(
          current_user,
          active_version,
          scopes: doorkeeper_token ? doorkeeper_token.scopes : []
        )
      end

      def active_version
        Version.find_by(tag: saved_scenario_params[:version]) || Version.default
      end
    end
  end
end

app/controllers/saved_scenarios_controller.rb
class SavedScenariosController < ApplicationController
  include Pagy::Method
  include Filterable

  load_resource only: %i[discard undiscard publish unpublish confirm_destroy]
  load_and_authorize_resource only: %i[show new create edit update destroy]

  before_action :require_user, only: %i[index]
  before_action :welcome_back

  before_action only: %i[publish unpublish] do
    authorize!(:update, @saved_scenario)
  end

  before_action only: %i[discard undiscard confirm_destroy] do
    authorize!(:destroy, @saved_scenario)
  end

  # GET /saved_scenarios
  def index
    @pagy_saved_scenarios, @saved_scenarios = pagy(ordered_user_saved_scenarios)
    @filters = {
      area_codes: area_codes_for_filter,
      end_years: user_saved_scenarios.pluck(:end_year).tally,
      versions: user_saved_scenarios.map(&:version).uniq
    }

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # Renders a partial of saved_scenarios based on turbo search and filters
  #
  # GET /saved_scenarios/list
  def list
    filtered = filter!(SavedScenario)
      .viewable_by?(current_user)
      .available
      .includes(:featured_scenario, :users)
      .order("updated_at DESC")

    @pagy_saved_scenarios, @saved_scenarios = pagy(filtered)

    respond_to do |format|
      format.html { render(
        partial: "saved_scenarios",
        locals: { saved_scenarios: @saved_scenarios, pagy_saved_scenarios: @pagy_saved_scenarios }
      ) }
      format.turbo_stream { render(:index) }
    end
  end

  # GET /saved_scenarios/1
  def show
  end

  # GET /saved_scenarios/new
  def new
    @saved_scenario = SavedScenario.new
  end

  # GET /saved_scenarios/1/edit
  def edit
  end

  # POST /saved_scenarios
  def create
    ActiveRecord::Base.transaction do
      @saved_scenario = SavedScenario.new(saved_scenario_params)

      if @saved_scenario.save
        SavedScenarioUser.create!(
          saved_scenario: @saved_scenario,
          user: current_user,
          role_id: User::Roles.index_of(:scenario_owner)
        )

        respond_to do |format|
          format.html {
            redirect_to @saved_scenario, notice: t("scenario.succesful_update") }
        end
      else
        respond_to do |format|
          format.html { render :new, status: :unprocessable_entity }
        end
        # Rollback the transaction if the scenario save fails
        raise ActiveRecord::Rollback
      end
    end
  end

  # PATCH/PUT /saved_scenarios/1 or /saved_scenarios/1.json
  def update
    respond_to do |format|
      if @saved_scenario.update(saved_scenario_update_params)
        format.html {
 redirect_to @saved_scenario, notice: t("scenario.succesful_update") }
        format.json { render :show, status: :ok, location: @saved_scenario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @saved_scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_destroy
    render :confirm_destroy, layout: "application"
  end

  # DELETE /saved_scenarios/1 or /saved_scenarios/1.json
  def destroy
    @saved_scenario.destroy
    flash.notice = t("scenario.trash.deleted_flash")
    redirect_to discarded_index_path
  end

  # Makes a scenario public.
  def publish
    @saved_scenario.update(private: false)

    ApiScenario::UpdatePrivacy.call_with_ids(
      engine_client(@saved_scenario.version),
      @saved_scenario.all_scenario_ids,
      private: false
    )

    redirect_to saved_scenario_path(@saved_scenario)
  end

  # Makes a scenario private.
  def unpublish
    @saved_scenario.update(private: true)

    ApiScenario::UpdatePrivacy.call_with_ids(
      engine_client(@saved_scenario.version),
      @saved_scenario.all_scenario_ids,
      private: true
    )

    redirect_to saved_scenario_path(@saved_scenario)
  end

  # Soft-deletes the scenario so that it no longer appears in listings.
  #
  # PUT /saved_scenarios/:id/discard
  def discard
    unless @saved_scenario.discarded?
      @saved_scenario.discarded_at = Time.zone.now
      @saved_scenario.save(touch: false)

      flash.notice = t("trash.discarded_flash")
      flash[:undo_params] = undiscard_saved_scenario_path(@saved_scenario)
    end

    redirect_back(fallback_location: saved_scenarios_path)
  end

  # Removes the soft-deletes of the scenario.
  #
  # PUT /saved_scenarios/:id/undiscard
  def undiscard
    unless @saved_scenario.kept?
      @saved_scenario.discarded_at = nil
      @saved_scenario.save(touch: false)

      flash.notice = t("trash.undiscarded_flash")
      flash[:undo_params] = discard_saved_scenario_path(@saved_scenario)
    end

    redirect_back(fallback_location: discarded_path)
  end

  private

  def user_saved_scenarios
    @user_saved_scenarios ||= current_user
      .saved_scenarios
      .available
      .includes(:featured_scenario, :users)
  end

  def ordered_user_saved_scenarios
    user_saved_scenarios.order("updated_at DESC")
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_saved_scenario
    @saved_scenario = SavedScenario.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def saved_scenario_params
    params.require(:saved_scenario).permit(
      :scenario_id, :scenario_id_history, :title,
      :description, :area_code, :end_year, :private,
      :created_at, :updated_at, :discarded_at
    )
  end

  # Only allow a list of trusted parameters through.
  def saved_scenario_update_params
    params.require(:saved_scenario).permit(
      :title, :description
    )
  end

  # Make sure to group all dup area_codes for nl together
  def area_codes_for_filter
    area_codes = user_saved_scenarios.group(:area_code).count

    dups = area_codes.select { |k, _v| SavedScenario::AREA_DUPS.include?(k) }

    if dups.size > 1
      area_codes = area_codes.except(*dups.keys)
      area_codes[dups.keys.first] = dups.sum { |_k, v| v }
    end

    area_codes = area_codes.sort_by { |_k, v| v }.reverse
  end
end

app/helpers/saved_scenario_helper.rb
# frozen_string_literal: true

module SavedScenarioHelper
  # Returns true if there is a special warning for the scenario
  #
  # Current use: dataset 2023 update for Dutch regions. Show banner
  # when scenario on latest with elegible dataset and updated before Oct 2nd
  def warning_for(saved_scenario)
    return false unless saved_scenario.version.default
    return false unless saved_scenario.updated_at < Date.new(2024, 10, 2)

    %w[GM ES PV].any? { |code| saved_scenario.area_code.start_with?(code) } && saved_scenario.area_code != "ES_spain"
  end
end

app/views/saved_scenarios/_block_right_menu.html.erb
<% content_for :block_right do %>
  <div class="flex flex-col">
    <%= render(SavedScenarios::NavItem::Component.new(
      path: saved_scenario_path(saved_scenario),
      title: t('scenario_bar.info'),
      icon: 'information-circle',
      active: controller_name == 'saved_scenarios' && action_name == 'show')
    )%>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: saved_scenario_history_path(saved_scenario),
      title: t('scenario_bar.history'),
      icon: 'clock',
      active: controller_name == 'saved_scenario_history')
    )%>
    <% if saved_scenario.owner?(current_user) || current_user&.admin? %>
      <%= render(SavedScenarios::NavItem::Component.new(
        path: saved_scenario_users_path(saved_scenario),
        title: t('scenario_bar.manage_access'),
        icon: 'user-group',
        active: controller_name == 'saved_scenario_users')
      )%>
    <% end %>
  </div>

  <div class="border-l lg:border-l-0 lg:border-t flex flex-col border-solid border-gray-200 pr-5 lg:pr-0 lg:mt-10 lg:pt-10">

    <%= render(partial: "block_right_sub_options", locals: { saved_scenario: saved_scenario }) %>

  </div>
<% end %>

app/views/saved_scenarios/_block_right_sub_options.html.erb
<%= render(Hovercard::Component.new(
    path: '',
    text: t("scenario_bar.private.description.#{saved_scenario.private}")
  )) do %>
  <%= render(SavedScenarios::Publish::Component.new(
    path_on: publish_saved_scenario_path(saved_scenario),
    path_off: unpublish_saved_scenario_path(saved_scenario),
    status: saved_scenario.private,
    title: t("scenario_bar.private.#{saved_scenario.private}"),
    icon_on:'eye-slash',
    icon_off: 'eye',
    available: saved_scenario.collaborator?(current_user) && !saved_scenario.discarded?
  ))%>
<% end %>
<% if current_user&.admin? && !saved_scenario.discarded? %>
  <%= render(Hovercard::Component.new(
    path: '',
    text: t("scenario_bar.featured.description.#{saved_scenario.featured?}")
  )) do %>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: saved_scenario_feature_path(saved_scenario),
      title: t("scenario_bar.featured.#{saved_scenario.featured?}"),
      icon: saved_scenario.featured? ? 'star' : 'sparkles',
      active: controller_name == 'featured_scenarios',
      static: true)
    )%>
  <% end %>
<% end %>
<% if
  !(current_user&.admin? && saved_scenario.featured?) &&
  (saved_scenario.collaborator?(current_user) && !saved_scenario.discarded?)%>
  <%= render(Hovercard::Component.new(
      path: '',
      text: t("scenario_bar.edit.description")
    )) do %>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: edit_saved_scenario_path(saved_scenario),
      title: t("scenario_bar.edit.title"),
      icon: 'pencil',
      static: true,
      active: action_name == 'edit',
      data: { turbo: false }
    ))%>
  <% end %>
<% end %>
<% if saved_scenario.owner?(current_user)%>
  <%= render(Hovercard::Component.new(
    path: '',
    text: t("scenario_bar.discarded.description.#{saved_scenario.discarded?}", deleted_after: SavedScenario::AUTO_DELETES_AFTER.in_days.to_i)
  )) do %>
    <%= render(SavedScenarios::Publish::Component.new(
      path_on: undiscard_saved_scenario_path(saved_scenario),
      path_off: discard_saved_scenario_path(saved_scenario),
      status: saved_scenario.discarded?,
      title: t("scenario_bar.discarded.#{saved_scenario.discarded?}"),
      icon_on: 'arrow-uturn-up',
      icon_off: 'trash',
      available: saved_scenario.collaborator?(current_user)
    ))%>
  <% end %>
<% end %>
<% if saved_scenario.owner?(current_user) && saved_scenario.discarded? %>
  <%= render(Hovercard::Component.new(
    path: '',
    text: t("scenario_bar.destroy.description")
  )) do %>
    <%= render(SavedScenarios::NavItem::Component.new(
      path: confirm_destroy_saved_scenario_path(saved_scenario),
      title: t("scenario_bar.destroy.title"),
      icon: 'x-mark',
      static: true,
      data: { turbo_frame: 'modal' }
    ))%>
  <% end %>
<% end %>

app/views/saved_scenarios/_block_right_with_filters.html.erb
<% content_for :block_right do %>
  <% if has_saved_scenarios %>
    <%= form_with url: list_saved_scenarios_path,
      method: :get,
      data: { controller: "search-form", search_form_target: "form", turbo_frame: "saved_scenarios", 'turbo-method': "get" } do |form|
      %>
      <div class="flex flex-col pl-5">
        <div class="mb-5 flex text-midnight-800">
          <%= form.text_field :title,
            placeholder: t('saved_scenarios.search_by_title'),
            class: "p-2 text-sm",
            autocomplete: "off",
            data: { action: "input->search-form#search" }
          %>
          <%= heroicon 'magnifying-glass', options: {class: 'w-5 h-5 ml-2 my-auto'} %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/saved_scenarios/_saved_scenarios.html.erb
<%= turbo_frame_tag "saved_scenarios" do %>
  <%= render(PagyComponent.new(pagy_objects: pagy_saved_scenarios)) do %>
    <div id="saved_scenarios_list" class="grid grid-rows-10 gap-y-2">
      <% saved_scenarios.each do |saved_scenario| %>
        <%= render(SavedScenarios::Row::Component.new(path: saved_scenario_path(saved_scenario), saved_scenario: saved_scenario)) %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/saved_scenarios/confirm_destroy.html.erb
<%= render(ModalComponent.new(title: t('.title'))) do |modal| %>
  <%= turbo_frame_tag :modal do %>
    <%= form_for(@saved_scenario, url: saved_scenario_path(@saved_scenario), html: { method: :delete, data: { turbo: false } }) do |f| %>
      <div class="flex-col mb-10">
        <div class="flex text-red-600 mb-5">
          <span class="mr-5"><%= heroicon 'exclamation-triangle', options: { class: 'w-6 h-6' } %></span>
          <span class="text-base">
            <%= t('.warning_header') %>
          </span>
        </div>
        <p class="mb-2">
          <%= t('.warning') %>
        </p>
        <p class="text-sm text-midnight-450">
          <%= t('.irreversible') %>
        </p>
      </div>
      <div class="mt-6 pb-2 flex items-center gap-2">
        <%= button_tag t('.submit'), class: button_classes("text-base", size: :lg, color: :warning) %>
        <%= modal.close_link(t('identity.cancel'), saved_scenario_path(@saved_scenario), class: button_classes("text-base", size: :lg)) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/saved_scenarios/edit.html.haml
- content_for :title, "Editing #{@saved_scenario.localized_title(I18n.locale)}"
- content_for :menu_title, "Editing #{@saved_scenario.localized_title(I18n.locale)}"
= render(partial: "block_right_menu",  locals: { saved_scenario: @saved_scenario })

= form_for(@saved_scenario, url: saved_scenario_path(@saved_scenario), html: { method: :put, class: 'flex flex-col h-full' }) do |f|
  = f.label :title, t('scenario.title'), class: 'text-sm text-midnight-400 mb-2'
  = f.text_field :title, class: 'appearance-none w-1/2 rounded-md border-gray-200 mb-5'
  = f.rich_text_area :description, class: 'appearance-none resize-none rounded-md border-gray-200 h-full mb-5'

  .flex.mt-auto.mb-0
    = submit_tag t('scenario.save'), class: 'button w-1/4 bg-midnight-900 text-midnight-200'
    = link_to t('scenario.discard_changes'), saved_scenario_path(@saved_scenario), class: 'button w-1/4 ml-auto mr-0'

app/views/saved_scenarios/index.html.haml
- content_for :title, "#{t('saved_scenarios.title')} - #{t('meta.title')}"
- content_for :menu_title, t('saved_scenarios.title')

= render(partial: "block_right_with_filters", locals: {   |
  has_saved_scenarios: @saved_scenarios.present?,         |
  filters: @filters })                                    |

- if @saved_scenarios.present?
  = render(partial: "saved_scenarios", locals: {pagy_saved_scenarios: @pagy_saved_scenarios, saved_scenarios: @saved_scenarios})
- else
  =t('saved_scenarios.empty')

app/views/saved_scenarios/index.turbo_stream.erb
<%= turbo_stream.append "saved_scenarios_list" do %>
  <% @saved_scenarios.each do |saved_scenario| %>
    <%= render(SavedScenarios::Row::Component.new(path: saved_scenario_path(saved_scenario), saved_scenario: saved_scenario)) %>
  <% end %>
<% end %>
<%= turbo_stream.update "next_url" do %>
  <%= render(MorePagy::Component.new(pagy: @pagy_saved_scenarios)) %>
<% end %>

app/views/saved_scenarios/show.html.haml
- content_for :menu_title, @saved_scenario.localized_title(I18n.locale)
- content_for :title, "#{@saved_scenario.localized_title(I18n.locale)} - #{t('saved_scenarios.title')} - #{t('meta.title')}"
= render(partial: "block_right_menu", locals: { saved_scenario: @saved_scenario })

= render(SavedScenarios::Info::Component.new(path: "#{@saved_scenario.version.model_url}/saved_scenarios/#{@saved_scenario.id}/load", button_title: t('saved_scenarios.open'), saved_scenario: @saved_scenario, time: time_ago_in_words(@saved_scenario.updated_at), with_user: current_user.present?))

- if flash[:undo_params]
  = render(NoticeBanner::Component.new(path: flash[:undo_params], text: notice_message, button_text: "#{t('undo')}?"))

- if warning_for(@saved_scenario)
  = render(NoticeBanner::Component.new(path: "#{Version.default.model_url}/whats-new", text: t('saved_scenarios.scenario_warning.desc'), button_text: t('saved_scenarios.scenario_warning.learn'), icon: "exclamation-triangle", warning: true))

- if @saved_scenario.discarded?
  = render(NoticeBanner::TrashComponent.new(text: t('trash.notice.scenarios', deleted_after: SavedScenario::AUTO_DELETES_AFTER.in_days.to_i)))

.w-min
  = render(HovercardWithVersion::Component.new(version: @saved_scenario.version.tag))

.flex.gap-5.mt-5.mb-5.pb-5.border-b.border-solid.border-gray-200
  - if @saved_scenario.featured?
    = @saved_scenario.featured_owner_name
  - else
    = render(SavedScenarios::InfoUsers::Component.new(title: t('saved_scenarios.owners'), users: @saved_scenario.owners, color: 'bg-midnight-900' ,privacy: @saved_scenario.no_explicit_access?(current_user)))
    = render(SavedScenarios::InfoUsers::Component.new(title: t('saved_scenarios.collaborators'), users: @saved_scenario.collaborators, color: 'bg-midnight-990', privacy: @saved_scenario.no_explicit_access?(current_user)))
    = render(SavedScenarios::InfoUsers::Component.new(title: t('saved_scenarios.viewers'), users: @saved_scenario.viewers, color: 'bg-midnight-970', privacy: @saved_scenario.no_explicit_access?(current_user)))

.mt-5.show-description
  - if @saved_scenario.localized_description(I18n.locale).presence
    = @saved_scenario.localized_description(I18n.locale)
  - elsif @saved_scenario.description.blank? && @saved_scenario.collaborator?(current_user) && !@saved_scenario.discarded?
    =link_to edit_saved_scenario_path(@saved_scenario), class: 'hover:underline' do
      = t('scenario.no_description')
      = t('scenario.create_description')
  - elsif @saved_scenario.description.blank?
    = t('scenario.no_description')
  - else
    = @saved_scenario.description