config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  use_doorkeeper_openid_connect

  devise_for :users, path: 'identity', sign_out_via: %i[get post delete], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/passthru/last', to: 'passthru#last', as: :back_to_etm

  namespace :identity do
    get '/', to: redirect('/identity/profile')
    get 'profile', to: 'settings#index', as: :profile

    get 'change_name', to: 'settings#edit_name', as: :edit_name
    post 'change_name', to: 'settings#update_name'

    get 'change_email', to: 'settings#edit_email', as: :edit_email
    post 'change_email', to: 'settings#update_email'

    get 'change_password', to: 'settings#edit_password', as: :edit_password
    post 'change_password', to: 'settings#update_password'

    post 'change_scenario_privacy', to: 'settings#update_scenario_privacy'

    get 'subscription/:audience', to: 'newsletter#edit', as: :edit_subscription
    patch 'subscription/:audience', to: 'newsletter#update', as: :update_subscription

    resources :tokens, only: [:index, :new, :create, :destroy], as: :tokens
    resources :access_tokens, only: [:create], as: :access_tokens
    resources :authorized_applications, only: [:index], as: :authorized_applications
  end

  devise_scope :user do
    get 'identity/delete_account', to: 'users/registrations#confirm_destroy', as: :delete_account
  end

  root :to => "saved_scenarios#index"

  resources :saved_scenarios do
    resource :feature, only: %i[show create update destroy], controller: 'featured_scenarios' do
      get :confirm_destroy
    end

    collection do
      get :list
      post :list
      post :index
    end

    member do
      put :publish
      put :unpublish
      put :discard
      put :undiscard
      get :confirm_destroy
    end

    resources :users, controller: 'saved_scenario_users' do
      member do
        get :confirm_destroy
      end
    end

    get '/history' => 'saved_scenario_history#index'
    put '/history/:scenario_id' => 'saved_scenario_history#update',  as: :update_history
    put '/history/:scenario_id/restore' => 'saved_scenario_history#restore',  as: :restore_history
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: %i[index show create update destroy]
      resources :saved_scenarios, only: %i[index show create update destroy] do
        resources :users, only: %i[index create], controller: 'saved_scenario_users' do
          collection do
            put :update
            delete :destroy
          end
        end
      end
      resources :featured_scenarios, only: %i[index show] do
        collection { get :scenarios }
      end
      resources :versions, only: [:index]
    end
  end

  resources :collections, only: %i[index show new edit destroy update] do
    collection do
      get :list
      post :list
      get :new_transition
      post :create_transition
      post :create_collection, as: :create
      post :index
    end

    member do
      put :discard
      put :undiscard
      get :confirm_destroy
    end
  end

  resources :discarded do
    collection do
      get :index
      post :index
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/org')
    get 'org',              to: 'users#org'
    get 'user/:user_id',         to: 'users#edit',    as: :edit_user
    put 'user/:user_id',         to: 'users#update',  as: :update_user
    put 'user/:user_id/confirm', to: 'users#confirm', as: :confirm_user

    get 'applications', to: 'staff_applications#index'
    put 'applications', to: 'staff_applications#update'

    resources :users, only: [:index] do
      collection do
        get :list
        post :list
        post :index
      end
    end

    resources :featured_scenario_users

    resources :saved_scenarios, only: [:index] do
      collection do
        get :list
        post :list
        post :index
        post :batch_dump
      end
    end

    resources :collections, only: [:index] do
      collection do
        post :list
        get :list
        post :index
      end
    end
  end

  get :contact, to: 'static_pages#contact'
  post :send_message, to: 'static_pages#send_message'
  get :privacy, to: 'static_pages#privacy'
  get :terms,   to: 'static_pages#terms'
  get :collaborate,   to: 'static_pages#collaborate'
  # get :root,    to: 'static_pages#empty'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/featured_scenario_user.rb
class FeaturedScenarioUser < ApplicationRecord
  belongs_to :user, optional: true
  has_many :featured_scenarios, foreign_key: :owner_id, dependent: :destroy

  validate :user_or_name_must_exist

  def user_name
    name.presence || user.name
  end

  def user_or_name_must_exist
    if user.blank? && name.blank?
      errors.add(:base, "Either user or name must be present")
    end
  end
end

app/controllers/admin/featured_scenario_users_controller.rb
module Admin
  class FeaturedScenarioUsersController < ApplicationController
    before_action :set_featured_scenario_user, only: [ :update, :edit ]

    def index
      @featured_scenario_users = FeaturedScenarioUser.all
    end

    def edit;end

    def new
      @featured_scenario_user = FeaturedScenarioUser.new
    end

    def create
      @featured_scenario_user = FeaturedScenarioUser.new(featured_scenario_user_params)

      if @featured_scenario_user.save
        flash[:notice] = t("admin.users.edit.success")

        respond_to do |format|
          format.html { redirect_to(admin_featured_scenario_users_path) }

          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(:modal, ""),
              turbo_new_user,
              turbo_notice
            ]
          end
        end
      else
        render :new
      end
    end

    def update
      if @featured_scenario_user.update(featured_scenario_user_params.compact_blank)
        flash[:notice] = t("admin.users.edit.success")

        respond_to do |format|
          format.html { redirect_to(admin_featured_scenario_users_path) }

          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(:modal, ""),
              turbo_user,
              turbo_notice
            ]
          end
        end
      else
        render(:edit, status: :unprocessable_entity)
      end
    end

    private

    def set_featured_scenario_user
      @featured_scenario_user ||= FeaturedScenarioUser.find(params[:id])
    end

    def featured_scenario_user_params
      params.require(:featured_scenario_user).permit(:name, :user_id)
    end

    def turbo_user
      turbo_stream.replace(
        "user_#{@featured_scenario_user.id}",
        Admin::FeaturedUserRow::Component.new(
          user: @featured_scenario_user,
          path: edit_admin_featured_scenario_user_path(@featured_scenario_user),
        )
      )
    end

    def turbo_new_user
      turbo_stream.append(
        "featured_users",
        Admin::FeaturedUserRow::Component.new(
          user: @featured_scenario_user,
          path: edit_admin_featured_scenario_user_path(@featured_scenario_user),
        )
      )
    end
  end
end

app/views/admin/featured_scenario_users/edit.html.erb
<%= render(ModalComponent.new(title: t('.title'))) do |modal| %>
  <%= turbo_frame_tag :update_featured_scenario_user_form do %>
    <%= form_for(@featured_scenario_user, url: admin_featured_scenario_user_path, html: { method: :put }) do |f| %>
      <%= render(FormSteps::WrapperComponent.new) do |steps| %>
        <%= render(FormSteps::RowComponent.new(title: t('.name'), label_for: "featured_scenario_user_name")) do |row| %>
          <%= f.text_field :name, value: @featured_scenario_user.name, required: true, autofocus: true, autocomplete: 'name', class: "field" %>

          <% row.icon { heroicon 'identification', options: {class: 'w-5 h-5 mr-2'} } %>

          <% row.after_hint do %>
            <%= render(FieldErrorsComponent.new(record: @featured_scenario_user, attribute: :name)) %>
          <% end %>
        <% end %>

        <div class="mb-5">
          <%= t('.or') %>
        </div>

        <%= render(FormSteps::RowComponent.new(title: t('.user'), label_for: "featured_scenario_user_user")) do |row| %>
          <div class="relative">
            <%= f.select :user_id, options_from_collection_for_select(User.all.order(:name), "id", "name"), class: 'mb-2'%>
          </div>

          <% row.icon { heroicon 'user', options: {class: 'w-5 h-5 mr-2'} } %>

          <% row.after_hint do %>
            <%= render(FieldErrorsComponent.new(record: @featured_scenario_user, attribute: :user)) %>
          <% end %>
        <% end %>


        <div class="mt-6 pb-2 flex items-center gap-2">
          <%= button_tag t('.submit'), class: button_classes("text-base", size: :lg, color: :success) %>
          <%= modal.close_link(t('identity.cancel'), admin_featured_scenario_users_path, class: button_classes("text-base", size: :lg)) %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/featured_scenario_users/index.html.erb
<%- content_for :menu_title, 'Featured Users' %>
<%- content_for :title, 'Featured Users' %>
<%= render(partial: "/admin/block_right_menu") %>

<div class="text-midnight-450">
  <%= t('admin.featured_scenario_users.intro') %>
</div>

<div class="mt-10 text-midnight-400 text-sm">
  <%= "Featured users (#{@featured_scenario_users.count})"%>
</div>

<div class="mt-2 border border-gray-200 rounded-md p-5">
  <%= turbo_frame_tag :featured_users do %>
    <% @featured_scenario_users.each do |user| %>
      <%= render Admin::FeaturedUserRow::Component.new(
        user: user,
        path: edit_admin_featured_scenario_user_path(user),
      )%>
    <% end %>
  <% end %>
</div>

<div class="flex mt-5">
  <%= link_to "+ #{t('admin.featured_scenario_users.add')}", new_admin_featured_scenario_user_path, data: { turbo_frame: :modal }, class: button_classes("ml-auto mr-0", color: :primary) %>
</div>

app/views/admin/featured_scenario_users/new.html.erb
<%= render(ModalComponent.new(title: t('.title'))) do |modal| %>
  <%= turbo_frame_tag :update_featured_scenario_user_form do %>
    <%= form_for(@featured_scenario_user, url: admin_featured_scenario_users_path, html: { method: :post }) do |f| %>
      <%= render(FormSteps::WrapperComponent.new) do |steps| %>
        <%= render(FormSteps::RowComponent.new(title: t('.name'), label_for: "featured_scenario_user_name")) do |row| %>
          <%= f.text_field :name, value: @featured_scenario_user.name, required: true, autofocus: true, autocomplete: 'name', class: "field" %>

          <% row.icon { heroicon 'identification', options: {class: 'w-5 h-5 mr-2'} } %>

          <% row.after_hint do %>
            <%= render(FieldErrorsComponent.new(record: @featured_scenario_user, attribute: :name)) %>
          <% end %>
        <% end %>

        <div class="mb-5">
          <%= t('.or') %>
        </div>

        <%= render(FormSteps::RowComponent.new(title: t('.user'), label_for: "featured_scenario_user_user")) do |row| %>
          <div class="relative">
            <%= f.select :user_id, options_from_collection_for_select(User.all.order(:name), "id", "name"), required: false, include_blank: true, class: 'mb-2'%>
          </div>

          <% row.icon { heroicon 'user', options: {class: 'w-5 h-5 mr-2'} } %>

          <% row.after_hint do %>
            <%= render(FieldErrorsComponent.new(record: @featured_scenario_user, attribute: :user)) %>
          <% end %>
        <% end %>


        <div class="mt-6 pb-2 flex items-center gap-2">
          <%= button_tag t('.submit'), class: button_classes("text-base", size: :lg, color: :success) %>
          <%= modal.close_link(t('identity.cancel'), admin_featured_scenario_users_path, class: button_classes("text-base", size: :lg)) %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>