config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  use_doorkeeper_openid_connect

  devise_for :users, path: 'identity', sign_out_via: %i[get post delete], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/passthru/last', to: 'passthru#last', as: :back_to_etm

  namespace :identity do
    get '/', to: redirect('/identity/profile')
    get 'profile', to: 'settings#index', as: :profile

    get 'change_name', to: 'settings#edit_name', as: :edit_name
    post 'change_name', to: 'settings#update_name'

    get 'change_email', to: 'settings#edit_email', as: :edit_email
    post 'change_email', to: 'settings#update_email'

    get 'change_password', to: 'settings#edit_password', as: :edit_password
    post 'change_password', to: 'settings#update_password'

    post 'change_scenario_privacy', to: 'settings#update_scenario_privacy'

    get 'subscription/:audience', to: 'newsletter#edit', as: :edit_subscription
    patch 'subscription/:audience', to: 'newsletter#update', as: :update_subscription

    resources :tokens, only: [:index, :new, :create, :destroy], as: :tokens
    resources :access_tokens, only: [:create], as: :access_tokens
    resources :authorized_applications, only: [:index], as: :authorized_applications
  end

  devise_scope :user do
    get 'identity/delete_account', to: 'users/registrations#confirm_destroy', as: :delete_account
  end

  root :to => "saved_scenarios#index"

  resources :saved_scenarios do
    resource :feature, only: %i[show create update destroy], controller: 'featured_scenarios' do
      get :confirm_destroy
    end

    collection do
      get :list
      post :list
      post :index
    end

    member do
      put :publish
      put :unpublish
      put :discard
      put :undiscard
      get :confirm_destroy
    end

    resources :users, controller: 'saved_scenario_users' do
      member do
        get :confirm_destroy
      end
    end

    get '/history' => 'saved_scenario_history#index'
    put '/history/:scenario_id' => 'saved_scenario_history#update',  as: :update_history
    put '/history/:scenario_id/restore' => 'saved_scenario_history#restore',  as: :restore_history
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: %i[index show create update destroy]
      resources :saved_scenarios, only: %i[index show create update destroy] do
        resources :users, only: %i[index create], controller: 'saved_scenario_users' do
          collection do
            put :update
            delete :destroy
          end
        end
      end
      resources :featured_scenarios, only: %i[index show] do
        collection { get :scenarios }
      end
      resources :versions, only: [:index]
    end
  end

  resources :collections, only: %i[index show new edit destroy update] do
    collection do
      get :list
      post :list
      get :new_transition
      post :create_transition
      post :create_collection, as: :create
      post :index
    end

    member do
      put :discard
      put :undiscard
      get :confirm_destroy
    end
  end

  resources :discarded do
    collection do
      get :index
      post :index
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/org')
    get 'org',              to: 'users#org'
    get 'user/:user_id',         to: 'users#edit',    as: :edit_user
    put 'user/:user_id',         to: 'users#update',  as: :update_user
    put 'user/:user_id/confirm', to: 'users#confirm', as: :confirm_user

    get 'applications', to: 'staff_applications#index'
    put 'applications', to: 'staff_applications#update'

    resources :users, only: [:index] do
      collection do
        get :list
        post :list
        post :index
      end
    end

    resources :featured_scenario_users

    resources :saved_scenarios, only: [:index] do
      collection do
        get :list
        post :list
        post :index
        post :batch_dump
      end
    end

    resources :collections, only: [:index] do
      collection do
        post :list
        get :list
        post :index
      end
    end
  end

  get :contact, to: 'static_pages#contact'
  post :send_message, to: 'static_pages#send_message'
  get :privacy, to: 'static_pages#privacy'
  get :terms,   to: 'static_pages#terms'
  get :collaborate,   to: 'static_pages#collaborate'
  # get :root,    to: 'static_pages#empty'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/discarded_controller.rb
class DiscardedController < ApplicationController
  include Pagy::Method
  before_action :require_user

  def index
    discarded_resources = (
      current_user
        .saved_scenarios
        .discarded
        .includes(:featured_scenario, :users).to_a +
      current_user
        .collections
        .discarded.to_a
    ).sort_by(&:updated_at).reverse

    @pagy, @resources = pagy(:offset, discarded_resources, items: 10)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
end

app/views/discarded/_block_right.html.erb
<% content_for :block_right do %>
  <div class="flex flex-col">
    <%= render(SavedScenarios::NavItem::Component.new(
      path: discarded_index_path,
      title: t('trash.all'),
      icon: 'wallet',
      active: controller_name == 'discarded')
    )%>
  </div>
<% end %>

app/views/discarded/index.html.haml
- content_for :title, t('trash.title')
- content_for :menu_title, t('trash.title')

= render(partial: "block_right")

- if notice_message
  = render(NoticeBanner::Component.new(text: notice_message))

= turbo_frame_tag "discarded" do
  - if @resources.present?
    - @resources.each do |resource|
      - if resource.is_a?(SavedScenario)
        = render(SavedScenarios::Row::Component.new(path: saved_scenario_path(resource), saved_scenario: resource))
      - elsif resource.is_a?(Collection)
        = render(Collections::Row::Component.new(path: collection_path(resource), collection: resource))
    = turbo_frame_tag "next_url" do
      = render(MorePagy::Component.new(pagy: @pagy))
  - else
    .text-sm.text-midnight-400.mb-2= t('trash.empty.title')

    = t('trash.empty.description', deleted_after: SavedScenario::AUTO_DELETES_AFTER.in_days.to_i)

app/views/discarded/index.turbo_stream.erb
<%= turbo_stream.append "discarded" do %>
  <% @resources.each do |resource| %>
    <% if resource.is_a?(SavedScenario) %>
      <%= render(SavedScenarios::Row::Component.new(path: saved_scenario_path(resource), saved_scenario: resource)) %>
    <% elsif resource.is_a?(Collection) %>
      <%= render(Collections::Row::Component.new(path: collection_path(resource), collection: resource)) %>
    <% end %>
  <% end %>
<% end %>

<%= turbo_stream.replace "next_url" do %>
  <% if @pagy.next %>
    <%= render(MorePagy::Component.new(pagy: @pagy)) %>
  <% end %>
<% end %>